### ISSUE TITLE
support for transparent local vs remote secrets

### ISSUE THREAD

**Issue by priamai** [modal-labs/modal-client#1061]
When a function is executed remotely it should leverage the Secret class but when is run locally it should default to a library like dotenv.
How can we make this as easy as possible without excessive boilerplate code?

**Comment by erikbern** [comment]
Did you see the `from_dotenv` constructor? https://modal.com/docs/reference/modal.Secret#from_dotenv

But I'd love to understand your use case a bit more. What do you mean "when it's running locally"? Modal functions just read environment variables so if you're running the same code remotely vs locally, it should work in the same exact way (assuming the env vars are set up properly)

**Comment by priamai** [comment]
I know but this doesn't work for example, I am guessing when I run locally it doesn't call properly the dotenv?

```

@stub.function(secret=modal.Secret.from_dotenv(),schedule=modal.Period(seconds=3))
def test_connect():

    URI = os.environ["NEO4J_URI"]
    AUTH = (os.environ["NEO4J_USERNAME"], os.environ["NEO4J_PASSWORD"])

    with GraphDatabase.driver(URI, auth=AUTH) as driver:
        print(
            f'Checking connectivity: {datetime.now().strftime("%m/%d/%Y, %H:%M:%S")}'
        )

        driver.verify_connectivity()

@stub.local_entrypoint(name="test")
def run():
    # does NOT work
    test_connect.local()
    # does work
    test_connect.remote()
```

**Comment by erikbern** [comment]
Yeah we don't inject environment variables on local calls. You will have to set them yourself. I'm not sure if we want Modal to change the environment variables – seems a bit dangerous

**Comment by mwaskom** [comment]
Closing as this is expected (if a little confusing) behavior!
