### ISSUE TITLE
tracking individual job runs

### ISSUE THREAD

**Issue by sn0v** [modal-labs/modal-client#1088]
hi team, apologies if this isn't the right forum but i couldn't find a support link on modal.com

we were wondering if there is a unique taskID (or an API we can hit) to track the progress of an async modal job?

more background on our use case -

we've got a long running job on modal (several minutes, maybe more) where we trigger data export from our platform (labelbox) and upload it to a GCS bucket. ideally we'd like to track each run of this modal job (pending, running, failed, succeeded etc) via a unique task ID

thank you!

**Comment by aksh-at** [comment]
hey @sn0v, each function call has a `function_call_id` that you can use to get the [call graph](https://modal.com/docs/reference/modal.call_graph#modalcall_graph) of that function call:

```python
from modal.functions import FunctionCall

function_call_obj = FunctionCalll.from_id("fc-xyz")
call_graph = function_call_obj.get_call_graph()
```

These function call IDs are returned both from `.spawn()` or from web endpoints if you use [wait_for_response=False](https://modal.com/docs/guide/webhook-timeouts#wait_for_responsefalse). How are you kicking off these jobs?

**Comment by aksh-at** [comment]
(Also, we do have a community Slack for questions. You can find the invite link in the dashboard on the top right)

**Comment by thundergolfer** [comment]
Closing as answered :)
