### ISSUE TITLE
unable to install pandas via  `project_environment_image = Image.debian_slim().pip_install("pandas")`

### ISSUE THREAD

**Issue by Arslan-Mehmood1** [modal-labs/modal-client#1215]
**hi.py script**

```
import modal
from modal import Image

project_environment_image = Image.debian_slim().pip_install("pandas")
stub =  modal.Stub("Hi_Modal_App")

@stub.function(image=project_environment_image)
def say_hi():
	for i in range(10):
		print("Hi - Welcome to Modal!")

@stub.local_entrypoint()
def main():
	say_hi.remote()
```

**Error Log Below:**
(modal) arslan@Folio-1040-G2:~/nixense_vixion/To-Do/cog_wav2lip_modal$ modal run hi.py
✓ Initialized. View run at https://modal.com/arslan-mehmood1/apps/ap-CJ3WfA4Z3QMB0IGOuKsbRP
Building image im-yeCFWeGoCO5TXvQfJpD0K2

=> Step 0: FROM base

=> Step 1: RUN python -m pip install pandas 
Looking in indexes: http://pypi-mirror.modal.local:5555/simple
Collecting pandas
  Downloading http://pypi-mirror.modal.local:5555/simple/pandas/pandas-2.1.4.tar.gz (4.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 156.3 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [36 lines of output]
      + meson setup /tmp/pip-install-z9frykyj/pandas_a956f850e11a4b769dd8412aae7491ab /tmp/pip-install-z9frykyj/pandas_a956f850e11a4b769dd8412aae7491ab/.mesonpy-i_azceys/build -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --vsenv --native-file=/tmp/pip-install-z9frykyj/pandas_a956f850e11a4b769dd8412aae7491ab/.mesonpy-i_azceys/build/meson-python-native-file.ini
      The Meson build system
      Version: 1.2.1
      Source dir: /tmp/pip-install-z9frykyj/pandas_a956f850e11a4b769dd8412aae7491ab
      Build dir: /tmp/pip-install-z9frykyj/pandas_a956f850e11a4b769dd8412aae7491ab/.mesonpy-i_azceys/build
      Build type: native build
      Project name: pandas
      Project version: 2.1.4
      C compiler for the host machine: cc (gcc 10.2.1 "cc (Debian 10.2.1-6) 10.2.1 20210110")
      C linker for the host machine: cc ld.bfd 2.35.2
      C++ compiler for the host machine: c++ (gcc 10.2.1 "c++ (Debian 10.2.1-6) 10.2.1 20210110")
      C++ linker for the host machine: c++ ld.bfd 2.35.2
      Cython compiler for the host machine: cython (cython 0.29.37)
      Host machine cpu family: x86_64
      Host machine cpu: x86_64
      Program python found: YES (/usr/local/bin/python)
      Did not find pkg-config by name 'pkg-config'
      Found Pkg-config: NO
      Run-time dependency python found: YES 3.8
      Build targets in project: 53
      
      pandas 2.1.4
      
        User defined options
          Native files: /tmp/pip-install-z9frykyj/pandas_a956f850e11a4b769dd8412aae7491ab/.mesonpy-i_azceys/build/meson-python-native-file.ini
          buildtype   : release
          vsenv       : True
          b_ndebug    : if-release
          b_vscrt     : md
      
      Found ninja-1.11.1.git.kitware.jobserver-1 at /tmp/pip-build-env-v6e1nz_6/normal/bin/ninja
      
      Visual Studio environment is needed to run Ninja. It is recommended to use Meson wrapper:
      /tmp/pip-build-env-v6e1nz_6/overlay/bin/meson compile -C .
      
      meson-python: error: Unsupported Python version 3.8.15, expected >=3.9
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

[notice] A new release of pip is available: 23.1.2 -> 23.3.2
[notice] To update, run: pip install --upgrade pip
Terminating task due to error: failed to run builder command "python -m pip install pandas "

Caused by:
    container exit status: 1
Runner failed with exception: task exited with failure, status = exit status: 1
Stopping app - uncaught exception raised locally: RemoteError('Image build for im-yeCFWeGoCO5TXvQfJpD0K2 failed with the exception:\ntask exited with failure, status = exit status: 1').
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/arslan/.virtualenvs/modal/bin/modal:8 in <module>                                          │
│                                                                                                  │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 8 │   sys.exit(main())                                                                         │
│   9                                                                                              │
│                                                                                                  │
│ /home/arslan/.virtualenvs/modal/lib/python3.8/site-packages/modal/__main__.py:9 in main          │
│                                                                                                  │
│    8 │   setup_rich_traceback()                                                                  │
│ ❱  9 │   entrypoint_cli()                                                                        │
│   10                                                                                             │
│                                                                                                  │
│ /home/arslan/.virtualenvs/modal/lib/python3.8/site-packages/click/core.py:1157 in __call__       │
│                                                                                                  │
│   1156 │   │   """Alias for :meth:`main`."""                                                     │
│ ❱ 1157 │   │   return self.main(*args, **kwargs)                                                 │
│   1158                                                                                           │
│                                                                                                  │
│ /home/arslan/.virtualenvs/modal/lib/python3.8/site-packages/typer/core.py:778 in main            │
│                                                                                                  │
│   777 │   ) -> Any:                                                                              │
│ ❱ 778 │   │   return _main(                                                                      │
│   779 │   │   │   self,                                                                          │
│                                                                                                  │
│ /home/arslan/.virtualenvs/modal/lib/python3.8/site-packages/typer/core.py:216 in _main           │
│                                                                                                  │
│   215 │   │   │   with self.make_context(prog_name, args, **extra) as ctx:                       │
│ ❱ 216 │   │   │   │   rv = self.invoke(ctx)                                                      │
│   217 │   │   │   │   if not standalone_mode:                                                    │
│                                                                                                  │
│ /home/arslan/.virtualenvs/modal/lib/python3.8/site-packages/click/core.py:1688 in invoke         │
│                                                                                                  │
│   1687 │   │   │   │   with sub_ctx:                                                             │
│ ❱ 1688 │   │   │   │   │   return _process_result(sub_ctx.command.invoke(sub_ctx))               │
│   1689                                                                                           │
│                                                                                                  │
│ /home/arslan/.virtualenvs/modal/lib/python3.8/site-packages/click/core.py:1688 in invoke         │
│                                                                                                  │
│   1687 │   │   │   │   with sub_ctx:                                                             │
│ ❱ 1688 │   │   │   │   │   return _process_result(sub_ctx.command.invoke(sub_ctx))               │
│   1689                                                                                           │
│                                                                                                  │
│ /home/arslan/.virtualenvs/modal/lib/python3.8/site-packages/click/core.py:1434 in invoke         │
│                                                                                                  │
│   1433 │   │   if self.callback is not None:                                                     │
│ ❱ 1434 │   │   │   return ctx.invoke(self.callback, **ctx.params)                                │
│   1435                                                                                           │
│                                                                                                  │
│ /home/arslan/.virtualenvs/modal/lib/python3.8/site-packages/click/core.py:783 in invoke          │
│                                                                                                  │
│    782 │   │   │   with ctx:                                                                     │
│ ❱  783 │   │   │   │   return __callback(*args, **kwargs)                                        │
│    784                                                                                           │
│                                                                                                  │
│ /home/arslan/.virtualenvs/modal/lib/python3.8/site-packages/click/decorators.py:33 in new_func   │
│                                                                                                  │
│    32 │   def new_func(*args: "P.args", **kwargs: "P.kwargs") -> "R":                            │
│ ❱  33 │   │   return f(get_current_context(), *args, **kwargs)                                   │
│    34                                                                                            │
│                                                                                                  │
│ /home/arslan/.virtualenvs/modal/lib/python3.8/site-packages/modal/cli/run.py:178 in f            │
│                                                                                                  │
│   177 │   │                                                                                      │
│ ❱ 178 │   │   with run_stub(                                                                     │
│   179 │   │   │   stub,                                                                          │
│                                                                                                  │
│ /home/arslan/.virtualenvs/modal/lib/python3.8/site-packages/synchronicity/synchronizer.py:497 in │
│ proxy_method                                                                                     │
│                                                                                                  │
│ /home/arslan/.virtualenvs/modal/lib/python3.8/site-packages/synchronicity/combined_types.py:26   │
│ in __call__                                                                                      │
│                                                                                                  │
│ /usr/lib/python3.8/contextlib.py:171 in __aenter__                                               │
│                                                                                                  │
│   170 │   │   try:                                                                               │
│ ❱ 171 │   │   │   return await self.gen.__anext__()                                              │
│   172 │   │   except StopAsyncIteration:                                                         │
│                                                                                                  │
│ /home/arslan/.virtualenvs/modal/lib/python3.8/site-packages/modal/runner.py:140 in _run_stub     │
│                                                                                                  │
│   139 │   │   │   exc_info = e                                                                   │
│ ❱ 140 │   │   │   raise e                                                                        │
│   141 │   │   finally:                                                                           │
│                                                                                                  │
│ /home/arslan/.virtualenvs/modal/lib/python3.8/site-packages/modal/runner.py:94 in _run_stub      │
│                                                                                                  │
│    93 │   │   │   # Create all members                                                           │
│ ❱  94 │   │   │   await app._create_all_objects(                                                 │
│    95 │   │   │   │   stub._indexed_objects, app_state, environment_name, shell=shell, output_   │
│                                                                                                  │
│ /home/arslan/.virtualenvs/modal/lib/python3.8/site-packages/modal/app.py:106 in                  │
│ _create_all_objects                                                                              │
│                                                                                                  │
│   105 │   │   │   │   existing_object_id = tag_to_object_id.get(tag)                             │
│ ❱ 106 │   │   │   │   await resolver.load(obj, existing_object_id)                               │
│   107 │   │   │   │   self._tag_to_object_id[tag] = obj.object_id                                │
│                                                                                                  │
│ /home/arslan/.virtualenvs/modal/lib/python3.8/site-packages/modal/_resolver.py:131 in load       │
│                                                                                                  │
│   130 │   │                                                                                      │
│ ❱ 131 │   │   return await cached_future                                                         │
│   132                                                                                            │
│                                                                                                  │
│ /home/arslan/.virtualenvs/modal/lib/python3.8/site-packages/modal/_resolver.py:104 in loader     │
│                                                                                                  │
│   103 │   │   │   │   # TODO(erikbern): do we need existing_object_id for those?                 │
│ ❱ 104 │   │   │   │   await asyncio.gather(*[self.load(dep) for dep in obj.deps()])              │
│   105                                                                                            │
│                                                                                                  │
│ /home/arslan/.virtualenvs/modal/lib/python3.8/site-packages/modal/_resolver.py:131 in load       │
│                                                                                                  │
│   130 │   │                                                                                      │
│ ❱ 131 │   │   return await cached_future                                                         │
│   132                                                                                            │
│                                                                                                  │
│ /home/arslan/.virtualenvs/modal/lib/python3.8/site-packages/modal/_resolver.py:107 in loader     │
│                                                                                                  │
│   106 │   │   │   │   # Load the object itself                                                   │
│ ❱ 107 │   │   │   │   await obj._load(obj, self, existing_object_id)                             │
│   108 │   │   │   │   if existing_object_id is not None and obj.object_id != existing_object_i   │
│                                                                                                  │
│ /home/arslan/.virtualenvs/modal/lib/python3.8/site-packages/modal/image.py:318 in _load          │
│                                                                                                  │
│    317 │   │   │   if result.status == api_pb2.GenericResult.GENERIC_STATUS_FAILURE:             │
│ ❱  318 │   │   │   │   raise RemoteError(f"Image build for {image_id} failed with the exception  │
│    319 │   │   │   elif result.status == api_pb2.GenericResult.GENERIC_STATUS_TERMINATED:        │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RemoteError: Image build for im-yeCFWeGoCO5TXvQfJpD0K2 failed with the exception:
task exited with failure, status = exit status: 1

**Comment by mwaskom** [comment]
If you look at the traceback, it's trying to build pandas from source and then failing because your image is using Python 3.8 but the latest version of pandas is compatible only with Python 3.9+.

I am looking into why that is happening — it's not the right behavior, as pip should fall back to the latest version of pandas that supports the version of Python you (or your container) have and then install it from a wheel.

In the meantime, you could explicitly ask for a later version of Python in your image, e.g.

```python
Image.debian_slim(python_version="3.11").pip_install("pandas")
```

Or if you really need to use Python 3.8 for some reason, pin pandas as `pip_install("pandas<2.1")`.

**Comment by thundergolfer** [comment]
Thanks for the report @Arslan-Mehmood1, can confirm this install behavior is different from what is expected in other Python environments. Will work on a fix.

**Comment by thundergolfer** [comment]
Thanks again for your report @Arslan-Mehmood1. This has been fixed. Change will rollout over the next 24 hrs.
