### ISSUE TITLE
Update protobuf

### ISSUE THREAD

**Issue by julien-blanchon** [modal-labs/modal-client#1566]
I need to use a protobuf>4.0 for some workload (typically insighface take up to 30sec to launch because of protobuf 3, with protobuf 4 and 5 this is nearly instant, see https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/238#issuecomment-1903230961). However seems like modal is not liking it:

```raw
modal 0.61.1 requires protobuf!=4.24.0,<5.0,>=3.19, but you have protobuf 5.26.0 which is incompatible.
```

What did you suggest  ? Any reason why your blocking protobuf <5.0. Did you think I can install some 4 version ?

**Comment by mwaskom** [comment]
Hey, protobuf 5 is quite new and we haven't had a chance to test whether it causes any problems for modal. But as the error message suggests, you should be able to install protobuf 4 (aside from the specific 4.24.0 release, which had some issues).

**Comment by julien-blanchon** [comment]
Seems that everything is fine with `pip install --upgrade protobuf==4.*`. I'm closing the issue !

**Comment by mwaskom** [comment]
Hey, just flagging that we had a chance to test out protobuf 5.26.1 and didn't see any issues, so the latest release of the client will be marked as compatible with it.
