### ISSUE TITLE
Importing from local file or folder inside a function doesn't work

### ISSUE THREAD

**Issue by imrnh** [modal-labs/modal-client#1582]
**main.py**

from modal import Stub, web_endpoint, Image, Secret
stub = Stub()
env_img = Image.from_registry("usrname/tmp-env")

@stub.function(image=env_img)
def main():
    from core.hello import hello
    hello()
    return {"good": "GOOOOD"}

**core/hello.py**
import PIL

def hello():
    print("HELLO IS TRUE")
    
    
    
 ### **Tree**
 .
├── core
│   └── hello.py
└── main.py

The output when running `modal run --env=main main.py`

Traceback (most recent call last):
  File "/pkg/modal/_container_entrypoint.py", line 489, in handle_input_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 630, in run_input
    res = imp_fun.fun(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/main.py", line 8, in main
    from core.hello import hello
ModuleNotFoundError: No module named 'core'
Stopping app - uncaught exception raised locally: ModuleNotFoundError("No module named 'core'").
╭─ Error ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ No module named 'core'                                                                                                                                                              │
╰───

Urgent solve needed. Can anyone help please?

**Comment by imrnh** [comment]
Cannot import core output function because it import PIL which is only available after docker image is pulled.

**Comment by mwaskom** [comment]
Hi, I think you should be able to use a [`Mount`](https://modal.com/docs/reference/modal.Mount#modalmount) here to ensure that your code is available remotely.

By the way, you'll usually get a faster answer to usage questions on our [Slack](https://modal.com/slack).

**Comment by mwaskom** [comment]
Hope that answered your question — feel free to reach out on slack if not!

**Comment by imrnh** [comment]
Hey, thank you for your response. Yes, Mount worked.
