### ISSUE TITLE
ImportError: cannot import name 'GRPCError' from 'grpclib'

### ISSUE THREAD

**Issue by sandeepnmenon** [modal-labs/modal-client#1634]
I am following the steps in [Create your first app](https://modal.com/sandeepnmenon/apps)
```bash
pip install modal
python3 -m modal setup
```
I get the error
```bash

################################################################################
#             Something with the Modal installation seems broken.              #
#           Please email support@modal.com and we will try to help!            #
################################################################################

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/sandeepnmenon/venv-default/lib/python3.10/site-packages/modal/__init__.py", line 12, in <module>
    from ._tunnel import Tunnel, forward
  File "/home/sandeepnmenon/venv-default/lib/python3.10/site-packages/modal/_tunnel.py", line 7, in <module>
    from grpclib import GRPCError, Status
ImportError: cannot import name 'GRPCError' from 'grpclib' (/home/sandeepnmenon/venv-default/lib/python3.10/site-packages/grpclib/__init__.py)
```
I tried installing `pip install --upgrade grpclib`, but still same error.

**Comment by sandeepnmenon** [comment]
When I made the verison `grpclib==0.4.7`, it worked.

**Comment by mwaskom** [comment]
Hi, thanks for flagging. Glad you were able to sort it out for yourself but I am curious if there's anything we should do on our end in case this is an issue that others will run into. We actually already have `grpclib==0.4.7` in our `setup.cfg` so I am a little confused how that would have solved it for you. Do you have any idea what version you had installed previously, or if any other libraries were installed when you did that? (i.e. any chance you still have the pip logs in your console?)

By the way — what OS are you on?

**Comment by sandeepnmenon** [comment]
I was trying to install it in my local environment that I had setup previously for some other project. So not sure what was the exact version then. But as mentioned I did run `pip install --upgrade grpclib` and same error.
It worked for me, when I created a fresh virtual environment and installed modal and ran the setup command.

I am using Ubuntu 22.04 running on WSL.

**Comment by mwaskom** [comment]
Hm, I am a little confused. If I make a new venv and install an older version of grpclib

```
$ python3.11 -m venv venv/grpclib-error
$ . venv/grpclib-error/bin/activate
$ pip install grpclib==0.4.3
```

then install modal

```
$ pip install modal
```

it updates grpclib to the version pinned in the modal setup.cfg

```
  Attempting uninstall: grpclib
    Found existing installation: grpclib 0.4.3
    Uninstalling grpclib-0.4.3:
      Successfully uninstalled grpclib-0.4.3
Successfully installed aiohttp-3.9.3 aiosignal-1.3.1 aiostream-0.5.2 annotated-types-0.6.0 anyio-4.3.0 attrs-23.2.0 certifi-2024.2.2 click-8.1.7 fastapi-0.110.0 frozenlist-1.4.1 grpclib-0.4.7 idna-3.6 markdown-it-py-3.0.0 mdurl-0.1.2 modal-0.62.24 protobuf-5.26.1 pydantic-2.6.4 pydantic-core-2.16.3 pygments-2.17.2 rich-13.7.1 sigtools-4.0.1 sniffio-1.3.1 starlette-0.36.3 synchronicity-0.6.5 toml-0.10.2 typer-0.9.4 types-certifi-2021.10.8.3 types-toml-0.10.8.20240310 typing-extensions-4.10.0 watchfiles-0.21.0 yarl-1.9.4
```

0.4.7 is the latest version on pypi so it's not like there is a forward-compatibility issue.

**Comment by sandeepnmenon** [comment]
Did you try running `python3 -m modal setup` after installing? Because the error is thrown while running the setup command.

grpclib details in my environment that breaks
```
pip show grpclib
Name: grpclib
Version: 0.4.7
Summary:
Home-page:
Author:
Author-email:
License:
Location: /home/sandeepnmenon/venv-default/lib/python3.10/site-packages
Requires:
Required-by: modal
```

grpc details in my environment where it works
```
pip show grpclib
Name: grpclib
Version: 0.4.7
Summary: Pure-Python gRPC implementation for asyncio
Home-page: https://github.com/vmagamedov/grpclib
Author: Vladimir Magamedov
Author-email: vladimir@magamedov.com
License: BSD-3-Clause
Location: /home/sandeepnmenon/github/venv-rag/lib/python3.10/site-packages
Requires: h2, multidict
Required-by: modal
```

So seems like the issue is not with just the version. What solved for me was to create a new fresh environment and install modal.

**Comment by mwaskom** [comment]
Yes, setup runs fine for me after this sequence of events.

Is there any chance that your other environment has a library called `grpclib` that is different from the library on PyPI? Do you install anything from alternate channels?

**Comment by mwaskom** [comment]
Haven't heard of any other users having similar issues and it works on a fresh install so I'm going to chalk this to something idiosyncratic about your pre-existing environment. Feel free to ping if you run across it again and can share a reproducible recipe for triggering it.
