### ISSUE TITLE
What best describe hardware of A800 (80 GB), H800 and H20 with add of modal?

### ISSUE THREAD

**Issue by yiakwy-xpu-ml-framework-team** [modal-labs/modal-client#1736]
## Question

I found modal has limited description of NVIDIA datacenter GPUs. We currently extensively use A800, H800 and H20. What best describe them ?

**Comment by mwaskom** [comment]
Hi, you can see a list of the GPU types that we support in our pricing page: https://modal.com/pricing

Feel free to reach out in slack with other questions. I’m going to close this thread to keep the issue tracker focused on bugs in the Modal client library itself.
