### ISSUE TITLE
How to run notebook with conda environment?

### ISSUE THREAD

**Issue by Iven2132** [modal-labs/modal-client#1743]
How to run notebook with conda environment? Doing `modal launch jupyter --image conda --gpu a10g ` didn't work gives error

` => Step 0: FROM conda time="2024-04-23T15:17:47Z" level=fatal msg="initializing source docker://conda:latest: reading manifest latest in docker.io/library/conda: requested access to the resource is denied" Terminating task due to error: command skopeo copy docker://conda oci:... had exit status: 1 Runner failed with exception: task exited with failure, status = exit status: 1 Stopping app - uncaught exception raised locally: `

**Comment by mwaskom** [comment]
Hi, the argument for `--image` needs to be an image on dockerhub; the error message is telling you that the string `conda` does not point at a valid image. Hope that helps!

**Comment by Iven2132** [comment]
> Hi, the argument for `--image` needs to be an image on dockerhub; the error message is telling you that the string `conda` does not point at a valid image. Hope that helps!

Oh, I see got it, Can you tell how to start notebook with one A100 of 80gb?

**Comment by Iven2132** [comment]
@mwaskom But I'm getting still errors running modal launch jupyter --gpu a100 --image continuumio/anaconda3

Error:
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/root/run_jupyter.py", line 30, in wait_for_port
    raise TimeoutError("Waited too long for port 8888 to accept connections") from exc
TimeoutError: Waited too long for port 8888 to accept connections
```

**Comment by Iven2132** [comment]
> It's not super obvious but you can do `--gpu a100-80gb`

Yeah, Can you tell me - How can I fix that timeout error?

**Comment by mwaskom** [comment]
I have tried your command line a few times and have not run into it. Perhaps it's an issue on your system. Are you running anything else on port 8888?

**Comment by Iven2132** [comment]
> I have tried your command line a few times and have not run into it. Perhaps it's an issue on your system. Are you running anything else on port 8888?

No, are you sure you are running `modal launch jupyter --gpu a100 --image continuumio/anaconda3` it gives that error with a100

**Comment by mwaskom** [comment]
Yes it worked for me when requesting an A100. But, those are not always immediately available. If you get stuck in a queue waiting for one, if could potentially trigger a timeout.
