### ISSUE TITLE
[Feature Request] Make installing modal dependancies in image optional

### ISSUE THREAD

**Issue by bonlime** [modal-labs/modal-client#1781]
Hey!

I've noticed that currently in `Image._registry_setup_commands` (https://github.com/modal-labs/modal-client/blob/b6f889afc43807f009b8677fc3adb778e44ed020/modal/image.py#L1074) you add extra lines to docker file to install modal + it's deps. In cases when everything is already installed this simply leads to extra build time + adds few extra MB to the image size due to pip cache.

Would it be possible to make it optional? Either through env var or through some flag?

**Comment by mwaskom** [comment]
By the way, our Images disable the pip cache be default. Are you observing otherwise?

**Comment by bonlime** [comment]
Thanks for a quick response. Regarding the pip cache - i've double checked, you're right, the cache is disabled. Regarding making it optional - it's for the case when the modal is already installed in the image and this step is unnecessary.

**Comment by bonlime** [comment]
okay, not it makes sense. Closing the issue
