### ISSUE TITLE
Docs page for "Apps, Stubs, and entrypoints" broken

### ISSUE THREAD

**Issue by zsiegel92** [modal-labs/modal-client#1862]
[This docs page](https://modal.com/docs/guide/apps) is broken.

I get the below result (even in incognito window). All other docs pages I tested work fine.

<img width="973" alt="Screenshot 2024-05-30 at 10 30 39 AM" src="https://github.com/modal-labs/modal-client/assets/26341564/ff32e703-51f5-4e9b-ab94-84342ee6620d">

**Comment by zsiegel92** [comment]
This one:

<img width="321" alt="Screenshot 2024-05-30 at 10 31 53 AM" src="https://github.com/modal-labs/modal-client/assets/26341564/31f97763-f425-4dbf-91cb-d2e5e39d7b03">

**Comment by zsiegel92** [comment]
It's treating "docs" as profile, "guide" as environment, and "apps" as "modal dashboard for apps".

I guess routing precedence really wants users to be allowed to create a profile called "docs" and an environment called "guide" if they so wish.

Quick fix would be to move that docs page to "https://modal.com/docs/guide/apps_stubs_and_entrypoints"

**Comment by mwaskom** [comment]
This appears to be working as expected now; thanks for reporting!

**Comment by zsiegel92** [comment]
@luiscape @mwaskom @RohanArepally y'all rock, thanks so much.
