### ISSUE TITLE
Calling deploy_app(app) inside a class raises InvalidError

### ISSUE THREAD

**Issue by gabrielfior** [modal-labs/modal-client#1879]
Hello,

I tried out Modal and liked it a lot, hence am trying to integrate it with an existing software package.

My file looks like this:
```python
class MyClass:
    def deploy_to_modal(
        self,
        cron_schedule: str,
    ):       

        image = Image.from_registry( "ghcr.io/MY-IMAGE")
        app = App(image=image, name=app_name)

        @app.function(schedule=Cron(cron_schedule))
        def run():
          self.run(market_type="NASDAQ")

        runner.deploy_app(app)
```

and the following error is called when I call the function `deploy_to_modal` above, like below:

```shell
if __name__ == "__main__":
  MyClass().deploy_to_modal("*/5 * * * *")
```

```
  File "/home/.../envs/env1/lib/python3.11/site-packages/modal/_utils/function_utils.py", line 102, in __init__
    raise InvalidError(
modal.exception.InvalidError: Cannot wrap `main.<locals>.execute_remote`: functions and classes used in Modal must be defined in global scope. If trying to apply additional decorators, they may need to use `functools.wraps`.
python-BaseException
```

Within the package I'm working on, the setup normally involves having a class which is called in a python script. Since we already have different deploy functions, `deploy_to_modal` would simply be another function inside that class.
Running `modal deploy my_file.py` is not an option we think is suitable for us, since this feature is part of a package that will be imported into other packages.

Guidance very much appreciated.

**Comment by mwaskom** [comment]
The problem is not calling `runner.deploy_app` inside the function, it's wrapping the `run` closure:

> functions and classes used in Modal must be defined in global scope

**Comment by gabrielfior** [comment]
> The problem is not calling `runner.deploy_app` inside the function, it's wrapping the `run` closure:
> 
> > functions and classes used in Modal must be defined in global scope

Understood, thanks. And what's the suggested way for wrapping a function with the `app.function` decorator inside a class method? I couldn't find an example in the documentation.

**Comment by mwaskom** [comment]
Hope that helps, feel free to reach out on Slack for help also!
