### ISSUE TITLE
Error with Streamlit example

### ISSUE THREAD

**Issue by tranhoangnguyen03** [modal-labs/modal-client#1884]
modal-http: internal server error: status Failure: TypeError("ClientSession.__init__() got an unexpected keyword argument 'max_line_size'")

**Comment by mwaskom** [comment]
Hi, are you sure that you're using an up-to-date version of `modal`? I just tried serving this example and it ran fine for me:

<img width="1851" alt="image" src="https://github.com/modal-labs/modal-client/assets/315810/32e09415-0fdc-4f9b-9218-3a9eb5ec0d3e">

We'll need more information about exactly what you're doing if the error persists after upgrading.

**Comment by xu-li** [comment]
I downgraded the modal package as a temporary solution. `pip install modal==0.62.203 --force`. 

The `max_line_size` was introduced 4 days ago. See [this commit](https://github.com/modal-labs/modal-client/commit/376bca5078b980045b5b28ba861a5264129f5848). 

@ekzhang may have more information.

**Comment by ekzhang** [comment]
Looks like that option might not work for image builder version 2023.12, which has aiohttp 3.8.3. I can see if I can find an alternative.
