### ISSUE TITLE
Feat: Enabling GPU during Memory Snapshotting

### ISSUE THREAD

**Issue by Goktug** [modal-labs/modal-client#1997]
When I attempt to start ComfyUI using the `@modal.enter(Snap=True)` function, the system performs a check on the GPU values after initiation. Although the function does not specifically utilize the GPU, it still necessitates their presence. So during this phase, an error occurs because GPUs are not available.

Enhancement Request:
If you could enable GPU during memory snapshotting, it would allow us to cache the more resource-intensive parts of the workflow. This improvement would significantly enhance performance/startup time.

Inquiry:
I understand this is a beta feature, but I am curious about the timeline for implementing this functionality. Could you provide any details on when we might expect this enhancement?

Thanks

**Comment by luiscape** [comment]
Hi @Goktug, that's a known limitation at the moment, unfortunately. We have been exploring approaches--including [`cuda-checkpoint`](https://github.com/NVIDIA/cuda-checkpoint)--to expose GPUs during checkpointing (and _also_ to checkpoint GPU memory) but we are not there yet.

We describe those limitations in our docs (https://modal.com/docs/guide/memory-snapshot#known-limitations).

I'll close this issue for bookkeeping. I'll post updates whenever we make progress here.

**Comment by luiscape** [comment]
I am unfamiliar with ComfyUI's initialization routine. You can control how GPUs are queried and used using Modal classes. In [this page](https://modal.com/docs/guide/memory-snapshot#controlling-snapshot-memory) we include an example where one would load a model first on CPU and then move it to a GPU whenever the GPU is available. Maybe that works?

**Comment by nichady** [comment]
Looks like they're working on this
#3340

**Comment by luiscape** [comment]
@nichady that's right we have an alpha version of GPU snapshots coming soon.
