### ISSUE TITLE
(dashboard frontend) Modal app function execution dashboard table gets messed up after changing "status" filter

### ISSUE THREAD

**Issue by zsiegel92** [modal-labs/modal-client#2007]
1. Click on an App's function to see a "Function Calls" table
<img width="1034" alt="Screenshot 2024-07-12 at 12 59 40 PM" src="https://github.com/user-attachments/assets/80638e71-0ea9-440f-a775-511d10dbbfd0">

2. Filter for "Status: Errors" and/or "Status: Completed". 
<img width="1011" alt="Screenshot 2024-07-12 at 1 00 11 PM" src="https://github.com/user-attachments/assets/58b43532-5b85-43f1-af08-34fef82ee0f7">

3. Reset filter to "Status: Any" and the table fields will appear in the wrong columns:
<img width="1098" alt="Screenshot 2024-07-12 at 12 59 26 PM" src="https://github.com/user-attachments/assets/9b19f4f4-2a74-4c2f-bfb0-4540888bbeed">

Possibly related - the browser Dev tools show some issues on the "Function Calls" route that don't seem to appear anywhere else for me.
<img width="772" alt="Screenshot 2024-07-12 at 1 01 40 PM" src="https://github.com/user-attachments/assets/27b7fb3f-fa0d-4f2d-ba94-be78086a0066">
<img width="761" alt="Screenshot 2024-07-12 at 1 04 12 PM" src="https://github.com/user-attachments/assets/cd9aa88b-68d5-4ffe-8a98-47a4797889ce">

**Comment by RohanArepally** [comment]
@zsiegel92 thanks for the report! This should be fixed now.
