### ISSUE TITLE
`CloudBucketMount` with `bucket_endpoint_url` fails for third-party S3 proxy

### ISSUE THREAD

**Issue by zsiegel92** [modal-labs/modal-client#2008]
[The `CloudBucketMount` docs](https://modal.com/docs/reference/modal.CloudBucketMount) describe usage of the `bucket_endpoint_url` parameter with non-S3 providers. Is this supported for S3? I am unable to mount an S3 bucket that requires this endpoint with `CloudBucketMount` (though I can interact with it just fine with `boto3` and the AWS CLI).

Bucket-mounting code (with fake values):

```python
bucket = modal.CloudBucketMount(
    "bucketname",
    bucket_endpoint_url="https://bucketurl",
    secret=modal.Secret.from_name("aws-credentials-secret"),
    read_only=True,
)
```
Executing functions with this as a volume fails. It stopped working when configuration of the S3 bucket was changed to require an `endpoint_url` parameter in boto3; using this value in `bucket_endpoint_url` seems to not work.

----

**Note** - the bucket and corresponding Modal secret are not misconfigured. The following commands succeed.

The following works in a Modal function with the same secret (and locally with those environment variables set):
```python
import os
import boto3

S3_KEY = os.environ.get("AWS_ACCESS_KEY_ID")
S3_SECRET = os.environ.get("AWS_SECRET_ACCESS_KEY")
S3_BUCKET = "bucketname"
s3 = boto3.client(
    "s3",
    aws_access_key_id=S3_KEY,
    aws_secret_access_key=S3_SECRET,
    # works with no region_name
    # region_name="us-west-1", # works
    # region_name="us-east-1", # works
    endpoint_url="https://bucketurl",
)

file_bytes = s3.get_object(Bucket=S3_BUCKET, Key="objectkey")['Body']
```

Also, with those environment variables set, the following lists files:

```sh
aws s3 ls s3://bucketname --endpoint-url https://bucketurl --recursive
```

**Comment by luiscape** [comment]
Hi @zsiegel92, what endpoint are you trying to use and what's the use-case for the endpoint? Are you using a [Service Endpoint](https://docs.aws.amazon.com/general/latest/gr/s3.html)?

**Comment by luiscape** [comment]
Hi @zsiegel92, thanks for reaching out. I've followed-up via email. Feel free to reach out via DM on Slack. :)

**Comment by zsiegel92** [comment]
@luiscape I think we can close this, the provider let us know they had actually moved the bucket to Azure with some sort of service that provides *most but not all* of the AWS S3 API. I don't think this is a Modal issue, though it's possible you could support it. If you want more details about the bucket please don't hesitate to reach out!

**Comment by zsiegel92** [comment]
@luiscape I think we can close this, the provider let us know they had actually moved the bucket to Azure with some sort of service that provides most but not all of the AWS S3 API. I don't think this is a Modal issue, though it's possible you could support it. If you want more details about the bucket please don't hesitate to reach out!
