### ISSUE TITLE
Importing a Modal function between Modal apps broken

### ISSUE THREAD

**Issue by johnml1135** [modal-labs/modal-client#2042]
According to [the documentation](https://modal.com/docs/guide/trigger-deployed-functions), to import a Modal function between apps, we should do something like:
```
import modal

app = modal.App("another-app")
app.square = modal.Function.from_name("my-shared-app", "square")
...
```

But, in adding the function to the app, I get this error: `modal.exception.DeprecationError: Deprecated on 2024-03-25: App assignments of the form `app.x` or `app["x"]` are deprecated!`, which was added with PR #1894.  Yet, if I just deplare the function int he global scope (not under app.) I get this error: `modal.exception.ExecutionError: Function has not been hydrated with the metadata it needs to run on Modal.`.  How should I proceed?  Right now I have to use version 0.62.234 or else my code breaks.

**Comment by mwaskom** [comment]
Hi, sorry about the outdated documentation. You should be able to use `Function.lookup` here:

```python
import modal

app = modal.App("another-app")
square = modal.Function.lookup("my-shared-app", "square")


@app.function()
def cube(x):
    return x * app.square.remote(x)
```

**Comment by johnml1135** [comment]
That would be great - except that I keep getting `AttributeError: App has no member my_function`.  I am actually using Modal running pytest tests on GitHub actions - I don't know if that would be causing any of the difficulties.

**Comment by mwaskom** [comment]
Hm I have confirmed on my end that the suggested recipe in the docs works if you (a) remove the attribute assignment to the app / attribute reference when you call the function and (b) substitute `Function.lookup` for `Function.from_name` to avoid hydration errors. i.e. what's shown above.

Where is `my_function` coming from? Sounds like something from our examples but doesn't appear on the page you linked. Any chance you can share a repro of what you're running that isn't working?

**Comment by mwaskom** [comment]
I'm going to close as I can't reproduce this but feel free to follow up or reach out on Slack for more support!
