### ISSUE TITLE
Modal logs "eat" prefixes sometimes

### ISSUE THREAD

**Issue by zsiegel92** [modal-labs/modal-client#2091]
Some logs in the Modal browser client Logs viewer appear to have had line prefixes truncated. It's unclear to me when/why this occurs but it seems to occur most often when lines are prefixed with one or more tab `\t` characters.

If this is expected behavior and I should not print lines in a certain way please let me know.

Thank you!

**Comment by mwaskom** [comment]
Would be super helpful if you could show an example of what you mean, or better yet a reproducer that we could run. I tried this very basic script and it appeared to work as expected:

```
import modal

app = modal.App("nomnom")

@app.function()
def f():
    for i in range(5):
        print("\t" * i + f"I have {i} tabs!")
```

```
$ modal run eat_logs.py
✓ Initialized. View run at http://localhost:7601/apps/mwaskom/main/ap-Qzz1m6W2H9NVb0QxFf2aEK
✓ Created objects.
├── 🔨 Created mount /home/ec2-user/scratch/eat_logs.py
└── 🔨 Created function f.
Stopping app - local entrypoint completed.
I have 0 tabs!
        I have 1 tabs!
                I have 2 tabs!
                        I have 3 tabs!
                                I have 4 tabs!
```

**Comment by zsiegel92** [comment]
Hey @mwaskom thanks for the response!

> logs in the Modal browser client Logs viewer

the problem is not in the console, but in the browser client Logs viewer.

The following script reproduces the issue for me. The logs in my console are correct (second screenshot) but they are cut off in the browser logs viewer (first screenshot).

```python
import modal

app = modal.App(
    "test-logs-app",
)


@app.function()
def test_log():
    ss = """
Querying db:

        SELECT DISTINCT
            a.id as id
        from
            table_a a
            left join table_b b on b.company_id = a.id;
    """
    print(ss)


# python -m modal run --env main -i scratch/test_modal_logs.py
@app.local_entrypoint()
def main():
    test_log.remote()
```

![Screenshot 2024-08-14 at 11 01 19 AM](https://github.com/user-attachments/assets/7445a997-becb-4a49-9220-aa77645dd202)
![Screenshot 2024-08-14 at 11 02 03 AM](https://github.com/user-attachments/assets/da272b61-76d8-4790-833e-b36514889b10)


**Actually your script also produces this bug** (third screenshot):
![Screenshot 2024-08-14 at 11 04 09 AM](https://github.com/user-attachments/assets/3d0c5d35-f078-466a-85a6-5731ff1f18bf)

**Comment by mwaskom** [comment]
Thanks for clarifying that; I've passed it on to our frontend team.

Closing here as it's not a client issue.
