### ISSUE TITLE
Unable to execute commands on live container (<Status.INVALID_ARGUMENT: 3>, "Exec not supported on runtime 'runc'", None) 

### ISSUE THREAD

**Issue by srushti98** [modal-labs/modal-client#2133]
I have a container live in deployment.

When I run as per the documentation, 
`poetry run modal container exec <cointainer-id> /bin/bash`

I am getting an error

`(<Status.INVALID_ARGUMENT: 3>, "Exec not supported on runtime 'runc'", None)  `

**Comment by mwaskom** [comment]
Hi — if you reach out to support@modal.com someone should be able to help you with this. Thanks!
