### ISSUE TITLE
How to use a lifespan event?

### ISSUE THREAD

**Issue by fcossio** [modal-labs/modal-client#2146]
Hi, I see that there is a way to decorate functions with `@enter` for the `modal.cls` syntax. For FastAPI apps, the recommended way to do it is with a lifespan function. How can I use a lifespan? It would be very useful to load the model on startup. Without having to do major refactors to the app.

**Comment by mwaskom** [comment]
Hello, we added support for ASGI lifespan events in v0.64.97: https://modal.com/docs/reference/changelog#06497-2024-09-11
