### ISSUE TITLE
Async `.remote` and `.remote.aio` type definitions are incorrect

### ISSUE THREAD

**Issue by zsiegel92** [modal-labs/modal-client#2147]
Using Python 3.12.2 and `modal==0.64.52`.

---

Type definitions for the return value of `async_fn.remote(...)` and `async_fn.remote.aio(...)` both seem to be incorrect in the Modal client, at least in the version I'm using.

For example, this script:

```python
import modal

app = modal.App("testing-aio")


@app.function()
async def subroutine_async():
    return 1


@app.function()
async def fn_async():
    output = await subroutine_async.remote.aio()
    print("subroutine output:", output)
    return 1


@app.local_entrypoint()
def main():
    output = fn_async.remote()
    print("output:", output)
```

successfully prints:

```
output: 1
subroutine output: 1
```
which proves that these functions are running as expected, but my IDE thinks they are returning `Coroutine`s:

<img width="452" alt="Screenshot 2024-08-23 at 7 35 43 PM" src="https://github.com/user-attachments/assets/476f8c7a-5f16-48c2-902d-8c2b4afa8530">
<img width="455" alt="Screenshot 2024-08-23 at 7 36 05 PM" src="https://github.com/user-attachments/assets/fb75c939-f041-4e5e-8751-0760d12a7306">

My IDE thinks that the variable `output` assigned with `output = await ...` is a `Coroutine[Any, Any, Literal[1]]`, even though I `await`ed the output. That's doesn't agree with the runtime value. If I try to annotate it correctly, my IDE (using Pylance) complains:

<img width="846" alt="Screenshot 2024-08-23 at 7 43 06 PM" src="https://github.com/user-attachments/assets/7ed69283-ea6c-40d5-8d85-63815bf00b16">

Furthermore, as [the docs mention](https://modal.com/docs/guide/async), it is possible to call `fn_async.remote()` outside of an async function, which is cool, \**but this is not possible within an async function*\*, and my IDE has no idea of this (and the docs don't specify that):

That is, my IDE should have a problem with this:

```python
@app.function()
async def fn_async():
    output = await subroutine_async.remote()
    print("subroutine output:", output)
    return 1
```

which actually produces this runtime error:
```
│ ❱ 13 output = await subroutine_async.remote()
TypeError: object int can't be used in 'await' expression
```
but my IDE is in fact fine with this, and actually thinks that the return value is the one it failed to infer with the correct `.aio` usage:
<img width="344" alt="Screenshot 2024-08-23 at 7 42 01 PM" src="https://github.com/user-attachments/assets/fa28b8ea-bd28-467d-9329-225b26c92470">

**Any improvements to Modal SDK typing will greatly appreciated!** Thanks so much

**Comment by freider** [comment]
Thanks for filing this issue. It's a known limitation of the current type stubs, specifically when the underlying decorated function is async.
To fix, we'd have to add conditional type transforms using `@typing.overload` that returns different types depending on the return value of the decorated function, but I'll have to double check that it works end to end.

**Comment by zsiegel92** [comment]
@freider thanks for this response! It really does make a difference on my end. So much of my work involved calling functions with .remote and .spawn and if you just get the typing correctly on these that would be amazing.

It's a real bummer when an error shows up with a wrong input to `.remote` that a type-checker would have caught on a regular Python function call.

Thanks so much.
