### ISSUE TITLE
`modal.functions.gather` type-aware via generics

### ISSUE THREAD

**Issue by zsiegel92** [modal-labs/modal-client#2188]
Now that `.spawn()` is type-aware via [this PR](https://github.com/modal-labs/modal-client/pull/2155), `outputs = modal.functions.gather(*[my_function.spawn(job) for job in jobs])` is accepted by type-checkers, and since `.spawn` returns a generic `FunctionCall[R]` (where `my_function` returns `R`), it should be possible for `outputs` to be type-checked to the return type of `my_function` without any additional annotations.

Would have to [make the `gather` function](https://github.com/modal-labs/modal-client/blob/1c72b1ef253c82af418ecd6f7bcc09634e36902e/modal/functions.py#L1490-L1514) generic.

Note - I manually edit the generated `functions.pyi` in the Modal package to have this:

```python
class __gather_spec(typing_extensions.Protocol):
    def __call__(self, *function_calls: FunctionCall[R])->typing.Iterable[R]: ...
```

making my IDE the only IDE that knows the type of `gather(*fn_calls)`, which is nice (the annotation may be a bit wrong idk).

I'm not sure how y'all generate your `.pyi` files but maybe you could have a build step that edits them to match the true behavior; the modal SDK annotations seem to be overly pessimistic/broad.

**Comment by freider** [comment]
Yeah I think that would be a nice improvement and I think it should work, I can make a quick patch to see!

FYI the `.pyi` files are generated by calling `inv type-stubs` in the client repo (requires requirements.dev.txt to be installed).

**Comment by zsiegel92** [comment]
Thanks @freider for moving this along! Big quality of life improvement for me.
