### ISSUE TITLE
Add support for pixi (e.g. `pixi_install_from_pyproject`)

### ISSUE THREAD

**Issue by asmith26** [modal-labs/modal-client#2201]
Hi there, 

I see you support a poetry install from a pyproject.toml: https://modal.com/docs/reference/modal.Image#poetry_install_from_file

[pixi](https://pixi.sh/latest/) is really fast and growing in popularity, thus please consider supporting it.

Thanks for any help!

**Comment by mwaskom** [comment]
Going to close as we don't plan to prioritize a convenience method for pixi in the near term, but feel free to reach out if you are having trouble getting it to work through `Image.run_commands`, etc.
