### ISSUE TITLE
Modal Interactive in Vscode Desktop App

### ISSUE THREAD

**Issue by eitanturok** [modal-labs/modal-client#2476]
Hello. Big fan of modal here!

I was wondering what the best way is to run modal interactively in the vscode desktop app.

The command
```sh
modal launch vscode
```
launches vscode in the browser. How can I run this in the vscode desktop app instead of the browser? 

The command `modal launch vscode` connects to vscode via http ([source](https://github.com/modal-labs/modal-client/blob/291f09001e22f79458c2da27ba46534b1b6e3ebe/modal/cli/programs/vscode.py#L74)). Is there some way to use http to connect to the vscode desktop app rather than the in-browser vscode? I'm not to familiar with http...

I also looked at the developing and debugging [docs](https://modal.com/docs/guide/developing-debugging) but this does not mention anything about `modal launch`.

Thanks!

**Comment by mwaskom** [comment]
Hi — you might be able to use vscode remote development via our [tunnels](https://modal.com/docs/guide/tunnels) feature, for this analogous to the Jupyter example in the docs. Let us know if you get it working!

**Comment by mwaskom** [comment]
PS feel free to reach out on modal.com/slack, we're typically much faster to respond there!
