### ISSUE TITLE
modal.com/storage "Error displaying files"

### ISSUE THREAD

**Issue by zsiegel92** [modal-labs/modal-client#2575]
It's really nice to view a list of files in the browser and to be able to open one in the browser to inspect. Of course everyone should have other ways of interacting with their volume besides this.

Problem: most of my Modal volumes have a few thousand files and the browser shows this error message, and I can't view any files:

![Screenshot 2024-11-26 at 11 19 36 AM](https://github.com/user-attachments/assets/52b88555-8486-4a62-9555-fd05efa033f4)

Displaying a subset of files, possibly with pagination, possibly with search, with the ability to open the files as plaintext, would be great.

Bonus would be if, just like the "Secrets" view, there was a "Usage" tab that gave both a Python and a CLI script to view files in the volume. E.g.

```sh
 modal volume ls <currently-visited vol name> --env <currently-visited env name> | head -n 10
```
and maybe a minimal python script with `volume.listdir("")` for good measure (easy to forget that one).

Thanks so much!

## Extra Bonus

Would be additionally helpful if you can make the "Pretty-print" feature in Chrome work for these file previews:

![Screenshot 2024-11-26 at 11 53 22 AM](https://github.com/user-attachments/assets/209bd79b-50bf-4d78-b9e3-d3c424a88892)
![Screenshot 2024-11-26 at 11 53 52 AM](https://github.com/user-attachments/assets/8cce263c-c14f-45aa-85b9-881f4e67d47e)

I think you are sending a "Content-type: text/plain" header for all responses; I think if you just don't set content-type at all (or use "application/json" for `.json` files of course would work) Chrome will offer that functionality.

**Comment by mwaskom** [comment]
Thanks @zsiegel92 I can pass this on. Btw are you in our [Slack](https://modal.com/slack)? This issue tracker is just checked relatively small team that works on the Python SDK, but we have a ticketing system in Slack that makes it easier to route questions like this to more relevant engineers.

**Comment by ekzhang** [comment]
Note for Modal: we are tracking this internally in https://linear.app/modal-labs/issue/PRD-485/pagination-and-search-for-volume-viewer-with-large-number-of-files

No immediate plans to implement

**Comment by mwaskom** [comment]
Thanks for cross-posting! Will close here as we're tracking internally.
