### ISSUE TITLE
Logs stream into terminal and browser when running ephemeral app in same environment as deployed app

### ISSUE THREAD

**Issue by zsiegel92** [modal-labs/modal-client#2634]
As description says - do `modal run --env xyz app.py`  after you already have deployed the same app in the same environment with `modal deploy --env xyz app.py`.

The weird behavior is that logs from the deployed app show up in the terminal where the ephemeral app is running AND in the browser "App Logs" for the ephemeral app. This seems to happen whenever the deployed app logs anything while it is running.

**If anyone from the team does not know what I'm referring to** please let me know and I'll describe it in more detail and maybe forward some app IDs. I've observed this for a long time though so I'll be surprised if nobody is aware of this.

Thanks so much!

**Comment by mwaskom** [comment]
Hi, we're not aware of any behavior like this. Can you share some information that would allow us to reproduce it?

**Comment by zsiegel92** [comment]
@mwaskom wow I can't believe I'm the only one who's noticed this!

Easiest repro is the following:

```python
# python -m modal deploy --env staging scratch/repro_modal_logs_bug.py
# python -m modal run --env staging scratch/repro_modal_logs_bug.py
import modal
import time

app = modal.App("test_modal_logs_issue")


@app.function(
    schedule=modal.Period(seconds=5),
)
def fn_a():
    import datetime

    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    print(f"hello from A: {now}")


@app.function()
def fn_b():
    print("Staring function b!")
    time.sleep(60)
    print("Finishing function b!")


@app.local_entrypoint()
def main():
    fn_b.remote()

```

# Step 1 deploy

As the comments  at the top suggest, you should deploy it:

```sh
python -m modal deploy --env <your environment> thisfile.py
```

# Step 2 check deployed logs, should show content every 5 seconds

and then check the modal logs of the *deployed* app and you should see all the `hello from A: 2024-12-10 22:13:28` lines, as-expected.

# Step 3 run app ephemerally

```sh
python -m modal run --env <your environment> thisfile.py
```

and while `time.sleep` ticks away in `fn_b`, you should see the logs from `fn_a` stream into your terminal!

![Screenshot 2024-12-10 at 5 14 57 PM](https://github.com/user-attachments/assets/6233ff94-0861-4475-9f49-cdda7a99ac23)

# Step 4 confirm that this affects the logs broadly

Check modal.com/apps/... to view the logs from the EPHEMERAL (`modal run`) app and there too they include the logs from the deployed app:
![Screenshot 2024-12-10 at 5 16 30 PM](https://github.com/user-attachments/assets/f37ca8ad-e227-4608-b298-8b39a36b3a91)


...and if you're a user of the `modal app logs` CLI like I am you will see them there too...

**Comment by zsiegel92** [comment]
Excuse the typos ("staring function b") but anyway this reproduces the issue, if you do or don't experience this please let me know @mwaskom !

**Comment by mwaskom** [comment]
I think the issue here is just that we run scheduled functions for Apps in an ephemeral state. Here's an adapted repro:

```python
import os
import time
import modal

app = modal.App("repro-logs-bug")

@app.function(
    schedule=modal.Period(seconds=2),
    secrets=[modal.Secret.from_local_environ(["CONTEXT"])],
)
def f_a():
    context = os.environ["CONTEXT"]
    print(f"Running f_a! {context=}")


@app.function()
def f_b():
    for _ in range(20):
        print("Running f_b!")
        time.sleep(2)
```

```
$ CONTEXT=deployment modal deploy repro_log_bug.py
✓ Created objects.
├── 🔨 Created mount /home/ec2-user/scratch/repro_log_bug.py
├── 🔨 Created function f_a.
└── 🔨 Created function f_b.
✓ App deployed in 1.050s! 🎉

View Deployment: https://modal.com/apps/michael-modal-labs/main/deployed/repro-logs-bug
(modal) [devbox ~/scratch]
$ CONTEXT=ephemeral modal run repro_log_bug.py::f_b
✓ Initialized. View run at https://modal.com/apps/michael-modal-labs/main/ap-9pJYl2q6kKN4wClo7FlSKr
✓ Created objects.
├── 🔨 Created mount /home/ec2-user/scratch/repro_log_bug.py
├── 🔨 Created function f_a.
└── 🔨 Created function f_b.
Running f_b!
Running f_a! context='ephemeral'
Running f_b!
Running f_a! context='ephemeral'
Running f_b!
Running f_a! context='ephemeral'
Running f_b!
Running f_a! context='ephemeral'
```

Meanwhile

```
$ modal app logs repro-logs-bug
Running f_a! context='deployment'
Running f_a! context='deployment'
Running f_a! context='deployment'
Running f_a! context='deployment'
Running f_a! context='deployment'
Running f_a! context='deployment'
```

**Comment by zsiegel92** [comment]
Ah no way, I didn't realize it worked like that. I guess I was totally confused and assumed it was the deployed logs. 

Is it documented that scheduled functions run in an ephemeral app? Two questions/observations:

- I assume scheduled functions do not run if you specify the function you are running, e.g. when doing `modal run app.py::fn_b`, `fn_a` should not also run even if it is scheduled. If it does I think that's really unintuitive
- If the above is true, then this "run scheduled functions for Apps in an ephemeral state" concept is mostly a quirk of `local_entrypoint` specifically - that's kind of unintuitive.

Either way I think scheduled functions running in an ephemeral state should be documented either in [the `modal run` reference](https://modal.com/docs/reference/cli/run) or [the `App.local_entrypoint` reference](https://modal.com/docs/reference/modal.App#local_entrypoint). If it's documented somewhere already please point me in the right direction.

Anyway thanks for the response as always @mwaskom !

**Comment by zsiegel92** [comment]
Hey @mwaskom I hadn't used `modal.Secret.from_local_environ` before but that is a good tool to force usage of `MODAL_CONTEXT=EPHEMERAL modal run...` and `MODAL_CONTEXT=DEPLOYED modal deploy...`

Modal already provides a ([list of existing env vars](https://modal.com/docs/guide/environment_variables)) and I wonder if we could have a new one called something like `MODAL_IS_EPHEMERAL` or `MODAL_DEPLOYED_OR_EPHEMERAL` or `MODAL_STATE` or `MODAL_CONTEXT` that can take on values `EPHEMERAL` and `DEPLOYED`.

Then any scheduled function that users do NOT want running during testing can start with 

```
if os.environ.get("MODAL_CONTEXT") == "EPHEMERAL":
        return
```

Right now this is possible to use if our functions have with 

```python
    secrets=[modal.Secret.from_local_environ(["MODAL_CONTEXT"])],
```

but that adds boilerplate and forces us all to do `MODAL_CONTEXT=EPHEMERAL modal run` (or `modal serve`) and `MODAL_CONTEXT=DEPLOYED modal deploy`, which is easy to mess up outside of CI/CD.

So - is there any possibility of adding a `MODAL_CONTEXT`/`MODAL_STATE`/`MODAL_DEPLOYED_OR_EPHEMERAL` variable to all Modal runtimes? Would be a big QOL improvement for me personally.
